---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: http://172.28.128.1:9999/install.sh

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[demo::default]
    attributes:
